In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

In [ ]:
# Upload the (Using google colab) file on your google drive.
# Mount the data set on google drive(colab framework)
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from sklearn import preprocessing
from sklearn.preprocessing import Normalizer

#Reading dataset
data = pd.read_csv('/content/drive/MyDrive/Spambase_dataset.csv')
data.head()



word_freq_make:          ...  spam
0                     0.06  ...     1
1                     0.00  ...     1
2                     0.00  ...     1
3                     0.00  ...     1
4                     0.00  ...     1

[5 rows x 58 columns]

In [ ]:
#Generating X and Y Dataset
x = data[list(data.columns)]
x.pop('spam')
y = data['spam']
print(x)
print(y)

      word_freq_make:          ...  capital_run_length_total:   
0                        0.06  ...                          2259
1                        0.00  ...                           191
2                        0.00  ...                           191
3                        0.00  ...                            54
4                        0.00  ...                           112
...                       ...  ...                           ...
4594                     0.31  ...                            88
4595                     0.00  ...                            14
4596                     0.30  ...                           118
4597                     0.96  ...                            78
4598                     0.00  ...                            40

[4599 rows x 57 columns]
0       1
1       1
2       1
3       1
4       1
       ..
4594    0
4595    0
4596    0
4597    0
4598    0
Name: spam, Length: 4599, dtype: int64


In [ ]:
#2. Normalize the data set with your suitable choice.
transformer = Normalizer().fit(data)
x = transformer.transform(x)

print(x)
print(y)

[[2.59683978e-05 0.00000000e+00 3.07292708e-04 ... 4.25059392e-03
  2.09911216e-01 9.77710178e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.81192865e-02
  2.04911354e-01 9.78451717e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.81192868e-02
  2.04911357e-01 9.78451731e-01]
 ...
 [2.53812946e-03 0.00000000e+00 2.53812946e-03 ... 1.18784459e-02
  5.07625892e-02 9.98330921e-01]
 [1.22759766e-02 0.00000000e+00 0.00000000e+00 ... 1.46672345e-02
  6.39373781e-02 9.97423098e-01]
 [0.00000000e+00 0.00000000e+00 1.59858723e-02 ... 3.07420620e-02
  1.22968248e-01 9.83745986e-01]]
0       1
1       1
2       1
3       1
4       1
       ..
4594    0
4595    0
4596    0
4597    0
4598    0
Name: spam, Length: 4599, dtype: int64


In [ ]:
#Split the data set of 70-30% as train and test.
from sklearn.model_selection import train_test_split


X_train,X_test,Y_train,Y_test = train_test_split(x, y, test_size=0.3, random_state=101)

In [ ]:
#For Artifical Neural Networks we need to do feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# **Support Vector Machine**

In [ ]:
#3. Write a python code to develop a SVM model so that you can classify the spam or ham data set(1/0).
# "Support Vector Classifier"
from sklearn.svm import SVC  
clf = SVC(kernel='poly',degree=100) 
  
# fitting x samples and y classes 
clf.fit(X_train, Y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=100, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
#5.Predict the out come on 30% test data set.
Y_Pred = clf.predict(X_test)
print(Y_Pred)

[0 1 0 ... 0 0 1]


In [ ]:
#6. Diplay the confusion matrix, accuracy and other outcome metrics.
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_Pred)

array([[738,  84],
       [ 47, 511]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_Pred)

0.9050724637681159

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_Pred))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92       822
           1       0.86      0.92      0.89       558

    accuracy                           0.91      1380
   macro avg       0.90      0.91      0.90      1380
weighted avg       0.91      0.91      0.91      1380



# **Artifical Neural Networks**

In [ ]:
#3. Write a python code to develop an ANN  model so that you can classify the spam or ham data set(1/0).
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
mlp.fit(X_train, Y_train.values.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
#5.Predict the out come on 30% test data set.
predictions = mlp.predict(X_test)
print(predictions)

[0 0 0 ... 0 0 1]


In [ ]:
#6. Diplay the confusion matrix, accuracy and other outcome metrics.
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, predictions)

array([[771,  51],
       [ 48, 510]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, predictions)

0.9282608695652174

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,predictions))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94       822
           1       0.91      0.91      0.91       558

    accuracy                           0.93      1380
   macro avg       0.93      0.93      0.93      1380
weighted avg       0.93      0.93      0.93      1380



# **Decision Tree Algorithm**

In [ ]:
#3.Write a python code to develop a Decision Tree Algorithm model so that you can classify the spam or ham data set(1/0).

# import the regressor
from sklearn.tree import DecisionTreeRegressor 

# create a regressor object
regressor = DecisionTreeRegressor(random_state = 0) 
  
# fit the regressor with X and Y data
regressor.fit(X_train, Y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [ ]:
#5.Predict the out come on 30% test data set.

  
# test the output by changing values, like 3750
y_pred_dec = regressor.predict(X_test)
print(y_pred_dec)
  

[0. 0. 0. ... 0. 0. 1.]


In [ ]:
#6. Diplay the confusion matrix, accuracy and other outcome metrics.
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, y_pred_dec)

array([[748,  74],
       [ 63, 495]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, y_pred_dec)

0.9007246376811594

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred_dec))

              precision    recall  f1-score   support

           0       0.92      0.91      0.92       822
           1       0.87      0.89      0.88       558

    accuracy                           0.90      1380
   macro avg       0.90      0.90      0.90      1380
weighted avg       0.90      0.90      0.90      1380

